export type ModelCategory = 'Female' | 'Male' | 'Fashion' | 'Commercial' | 'Editorial'

export interface ModelMeasurements {
  bust?: string
  waist: string
  hips?: string
  chest?: string
  shoe: string
}

export interface Model {
  id: string
  name: string
  slug: string
  category: ModelCategory
  height: string
  measurements: ModelMeasurements
  hair: string
  eyes: string
  location: string
  experience: string
  specialties: string[]
  biography: string
  heroImage: string
  portfolioImages: string[]
  stats: { campaigns: number; editorials: number; runways: number }
}

export const models: Model[] = [
  {
    id: '1',
    name: 'Fatima',
    slug: 'fatima',
    category: 'Female',
    height: "5'8\" / 173cm",
    measurements: { bust: '34"', waist: '25"', hips: '35"', shoe: '37 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '3 Years',
    specialties: ['Modest Fashion', 'Editorial', 'Beauty'],
    biography:
      'Fatima brings a rare elegance to every frame — her presence commands attention while her warmth invites connection. Rooted in Cape Town, she has become one of définir\'s most distinctive voices in modest fashion and editorial work, redefining contemporary beauty standards with effortless grace and cultural pride.',
    heroImage: '/images/models/fatima/2.jpg',
    portfolioImages: [
      '/images/models/fatima/1.jpg',
      '/images/models/fatima/2.jpg',
      '/images/models/fatima/3.jpg',
      '/images/models/fatima/4.jpg',
      '/images/models/fatima/5.jpg',
    ],
    stats: { campaigns: 12, editorials: 28, runways: 6 },
  },
  {
    id: '2',
    name: 'Gustavo',
    slug: 'gustavo',
    category: 'Male',
    height: "6'0\" / 183cm",
    measurements: { chest: '38"', waist: '30"', shoe: '43 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '2 Years',
    specialties: ['Streetwear', 'Commercial', 'Lifestyle'],
    biography:
      'Gustavo is the embodiment of Cape Town\'s creative street culture — bold, fearless, and effortlessly stylish. With a natural charisma that translates across all formats, he brings an authentic energy to commercial and lifestyle campaigns that resonates with a new generation of South African audiences.',
    heroImage: '/images/models/gustavo/3.jpg',
    portfolioImages: [
      '/images/models/gustavo/1.jpg',
      '/images/models/gustavo/2.jpg',
      '/images/models/gustavo/3.jpg',
      '/images/models/gustavo/4.jpg',
      '/images/models/gustavo/5.jpg',
    ],
    stats: { campaigns: 8, editorials: 14, runways: 3 },
  },
  {
    id: '3',
    name: 'Hossanna',
    slug: 'hossanna',
    category: 'Female',
    height: "5'9\" / 175cm",
    measurements: { bust: '34"', waist: '26"', hips: '36"', shoe: '39 EU' },
    hair: 'Black',
    eyes: 'Brown',
    location: 'Cape Town',
    experience: '3 Years',
    specialties: ['Commercial', 'Sportswear', 'Lifestyle'],
    biography:
      'Hossanna\'s athletic build and natural confidence make her one of définir\'s most versatile female talents. Whether on the court or in the studio, she commands every environment with ease. Her work spans commercial campaigns, sportswear shoots, and lifestyle editorials across South Africa.',
    heroImage: '/images/models/hossanna/4.jpg',
    portfolioImages: [
      '/images/models/hossanna/1.jpg',
      '/images/models/hossanna/2.jpg',
      '/images/models/hossanna/3.jpg',
      '/images/models/hossanna/4.jpg',
      '/images/models/hossanna/5.jpg',
    ],
    stats: { campaigns: 15, editorials: 19, runways: 4 },
  },
  {
    id: '4',
    name: 'Jean Luc',
    slug: 'jean-luc',
    category: 'Male',
    height: "6'1\" / 185cm",
    measurements: { chest: '39"', waist: '30"', shoe: '44 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '4 Years',
    specialties: ['Editorial', 'High Fashion', 'Art Direction'],
    biography:
      'Jean Luc is a storyteller in front of the camera. His work is defined by an intense, cinematic quality that elevates every editorial he appears in. One of définir\'s leading male editorial talents, Jean Luc brings conceptual depth and visual intelligence to every collaboration — a rare combination in South African fashion.',
    heroImage: '/images/models/jean-luc/4.jpg',
    portfolioImages: [
      '/images/models/jean-luc/1.jpg',
      '/images/models/jean-luc/2.jpg',
      '/images/models/jean-luc/3.jpg',
      '/images/models/jean-luc/4.jpg',
      '/images/models/jean-luc/5.jpg',
    ],
    stats: { campaigns: 18, editorials: 44, runways: 12 },
  },
  {
    id: '5',
    name: 'Kendall',
    slug: 'kendall',
    category: 'Female',
    height: "5'9\" / 175cm",
    measurements: { bust: '33"', waist: '24"', hips: '35"', shoe: '38 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '2 Years',
    specialties: ['Fashion', 'Editorial', 'Commercial'],
    biography:
      'Kendall carries a quiet intensity that draws the eye immediately. Her ability to shift between soft editorial and bold commercial work has established her as one of définir\'s most adaptable female talents. Based in Cape Town, she is building a career defined by versatility, discipline, and a striking natural presence.',
    heroImage: '/images/models/kendall/3.jpg',
    portfolioImages: [
      '/images/models/kendall/1.jpg',
      '/images/models/kendall/2.jpg',
      '/images/models/kendall/3.jpg',
      '/images/models/kendall/4.jpg',
    ],
    stats: { campaigns: 9, editorials: 21, runways: 5 },
  },
  {
    id: '6',
    name: 'Kevin',
    slug: 'kevin',
    category: 'Male',
    height: "6'0\" / 183cm",
    measurements: { chest: '40"', waist: '30"', shoe: '43 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '5 Years',
    specialties: ['Editorial', 'Fine Art', 'High Fashion'],
    biography:
      'Kevin is one of définir\'s most sought-after editorial talents — a model whose work crosses the boundary between fashion and fine art. His commanding physical presence and fearless approach to conceptual shoots have produced some of the most striking images to come out of Cape Town\'s fashion scene. Kevin does not simply model — he transforms.',
    heroImage: '/images/models/kevin/1.jpg',
    portfolioImages: [
      '/images/models/kevin/1.jpg',
      '/images/models/kevin/2.jpg',
      '/images/models/kevin/3.jpg',
      '/images/models/kevin/4.jpg',
      '/images/models/kevin/5.jpg',
    ],
    stats: { campaigns: 22, editorials: 58, runways: 14 },
  },
  {
    id: '7',
    name: 'Laudice',
    slug: 'laudice',
    category: 'Male',
    height: "6'2\" / 188cm",
    measurements: { chest: '41"', waist: '32"', shoe: '45 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '4 Years',
    specialties: ['High Fashion', 'Formal', 'Luxury'],
    biography:
      'Laudice embodies the future of African luxury fashion. Tall, sharp, and effortlessly polished, he brings a powerful elegance to formal and high fashion work that few can match. His presence in a frame signals quality — brands across South Africa seek him out for their most prestigious campaigns.',
    heroImage: '/images/models/laudice/4.jpg',
    portfolioImages: [
      '/images/models/laudice/1.jpg',
      '/images/models/laudice/2.jpg',
      '/images/models/laudice/3.jpg',
      '/images/models/laudice/4.jpg',
      '/images/models/laudice/5.jpg',
    ],
    stats: { campaigns: 19, editorials: 36, runways: 22 },
  },
  {
    id: '8',
    name: 'Levi',
    slug: 'levi',
    category: 'Male',
    height: "6'0\" / 183cm",
    measurements: { chest: '39"', waist: '31"', shoe: '43 EU' },
    hair: 'Black',
    eyes: 'Brown',
    location: 'Cape Town',
    experience: '3 Years',
    specialties: ['Commercial', 'Lifestyle', 'Fitness'],
    biography:
      'Levi\'s infectious energy and natural warmth make him one of définir\'s most compelling commercial talents. His approachable good looks and genuine personality translate powerfully on camera — whether in a lifestyle shoot, brand campaign, or fitness editorial. He connects with audiences immediately and authentically.',
    heroImage: '/images/models/levi/1.jpg',
    portfolioImages: [
      '/images/models/levi/1.jpg',
      '/images/models/levi/2.jpg',
      '/images/models/levi/3.jpg',
      '/images/models/levi/4.jpg',
      '/images/models/levi/5.jpg',
    ],
    stats: { campaigns: 31, editorials: 22, runways: 4 },
  },
  {
    id: '9',
    name: 'Lilitha',
    slug: 'lilitha',
    category: 'Female',
    height: "5'10\" / 178cm",
    measurements: { bust: '34"', waist: '25"', hips: '36"', shoe: '38 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '4 Years',
    specialties: ['African Fashion', 'Editorial', 'Commercial'],
    biography:
      'Lilitha is a proud expression of African beauty and identity. Her work with African designers and contemporary fashion brands has placed her at the forefront of Cape Town\'s fashion movement. With a poised confidence and natural elegance, she brings cultural richness and modern sensibility to every image she creates.',
    heroImage: '/images/models/lilitha/4.jpg',
    portfolioImages: [
      '/images/models/lilitha/1.jpg',
      '/images/models/lilitha/2.jpg',
      '/images/models/lilitha/3.jpg',
      '/images/models/lilitha/4.jpg',
      '/images/models/lilitha/5.jpg',
    ],
    stats: { campaigns: 24, editorials: 41, runways: 18 },
  },
  {
    id: '10',
    name: 'Mike',
    slug: 'mike',
    category: 'Male',
    height: "6'1\" / 185cm",
    measurements: { chest: '40"', waist: '31"', shoe: '44 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '3 Years',
    specialties: ['Fashion', 'Editorial', 'Streetwear'],
    biography:
      'Mike brings a sharp, contemporary edge to every project. His look — effortlessly cool and culturally rooted — resonates across fashion, editorial, and streetwear markets. Based in Cape Town, Mike has built a reputation for reliability, creativity, and a powerful screen presence that brands consistently return to.',
    heroImage: '/images/models/mike/2.jpg',
    portfolioImages: [
      '/images/models/mike/1.jpg',
      '/images/models/mike/2.jpg',
      '/images/models/mike/3.jpg',
      '/images/models/mike/4.jpg',
      '/images/models/mike/5.jpg',
    ],
    stats: { campaigns: 16, editorials: 29, runways: 8 },
  },
  {
    id: '11',
    name: 'Prescilia',
    slug: 'prescilia',
    category: 'Female',
    height: "5'8\" / 173cm",
    measurements: { bust: '33"', waist: '24"', hips: '34"', shoe: '37 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '3 Years',
    specialties: ['Editorial', 'Alternative', 'Fashion'],
    biography:
      'Prescilia defies convention. Her bold, uncompromising approach to editorial work has made her one of définir\'s most distinctive female voices. She thrives in conceptual, high-contrast shoots where attitude and story take precedence — and she delivers both in abundance. An emerging force in Cape Town\'s editorial scene.',
    heroImage: '/images/models/prescilia/3.jpg',
    portfolioImages: [
      '/images/models/prescilia/1.jpg',
      '/images/models/prescilia/2.jpg',
      '/images/models/prescilia/3.jpg',
      '/images/models/prescilia/4.jpg',
      '/images/models/prescilia/5.jpg',
    ],
    stats: { campaigns: 10, editorials: 33, runways: 7 },
  },
  {
    id: '12',
    name: 'Salma',
    slug: 'salma',
    category: 'Female',
    height: "5'9\" / 175cm",
    measurements: { bust: '34"', waist: '25"', hips: '35"', shoe: '38 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '4 Years',
    specialties: ['Editorial', 'Modest Fashion', 'Beauty'],
    biography:
      'Salma possesses a rare stillness in front of the camera — a quality that makes her editorial work instantly compelling. Her black-and-white portraits have become some of définir\'s most celebrated images, capturing a depth of feeling and quiet power that transcends fashion. She is a model who makes you stop and look.',
    heroImage: '/images/models/salma/1.jpg',
    portfolioImages: [
      '/images/models/salma/1.jpg',
      '/images/models/salma/2.jpg',
      '/images/models/salma/3.jpg',
    ],
    stats: { campaigns: 14, editorials: 38, runways: 5 },
  },
  {
    id: '14',
    name: 'Thairah',
    slug: 'thairah',
    category: 'Female',
    height: "5'7\" / 170cm",
    measurements: { bust: '33"', waist: '24"', hips: '34"', shoe: '37 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '2 Years',
    specialties: ['Lifestyle', 'Commercial', 'Fashion'],
    biography:
      'Thairah brings a fresh, effortless energy that feels completely at home in Cape Town\'s outdoor lifestyle aesthetic. Her natural ease in front of the camera — whether in editorial or commercial settings — makes her one of définir\'s most exciting emerging talents. Warm, versatile, and instinctively photogenic.',
    heroImage: '/images/models/thairah/1.jpg',
    portfolioImages: [
      '/images/models/thairah/1.jpg',
      '/images/models/thairah/2.jpg',
      '/images/models/thairah/3.jpg',
      '/images/models/thairah/4.jpg',
    ],
    stats: { campaigns: 6, editorials: 11, runways: 2 },
  },
  {
    id: '15',
    name: 'Yaseen',
    slug: 'yaseen',
    category: 'Male',
    height: "6'0\" / 183cm",
    measurements: { chest: '38"', waist: '30"', shoe: '43 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '3 Years',
    specialties: ['Streetwear', 'Editorial', 'Urban Fashion'],
    biography:
      'Yaseen is the voice of Cape Town\'s urban creative scene. His editorial work blends streetwear culture with high fashion sensibility, creating images that feel both cinematic and authentic. Equally at home in a studio or on location, he brings a sharp visual intelligence and genuine style to every brief.',
    heroImage: '/images/models/yaseen/3.jpg',
    portfolioImages: [
      '/images/models/yaseen/1.jpg',
      '/images/models/yaseen/2.jpg',
      '/images/models/yaseen/3.jpg',
      '/images/models/yaseen/4.jpg',
      '/images/models/yaseen/5.jpg',
    ],
    stats: { campaigns: 11, editorials: 24, runways: 6 },
  },
  {
    id: '13',
    name: 'Simvuyele',
    slug: 'simvuyele',
    category: 'Male',
    height: "6'0\" / 183cm",
    measurements: { chest: '39"', waist: '30"', shoe: '43 EU' },
    hair: 'Black',
    eyes: 'Dark Brown',
    location: 'Cape Town',
    experience: '2 Years',
    specialties: ['Commercial', 'Lifestyle', 'Fashion'],
    biography:
      'Simvuyele brings a focused intensity and quiet confidence that makes him immediately striking on camera. His clean, versatile look works across commercial, lifestyle, and fashion briefs with equal power. A rising talent at définir, Simvuyele is establishing himself as one of Cape Town\'s most watch-worthy new faces.',
    heroImage: '/images/models/simvuyele/1.jpg',
    portfolioImages: [
      '/images/models/simvuyele/1.jpg',
      '/images/models/simvuyele/2.jpg',
      '/images/models/simvuyele/3.jpg',
    ],
    stats: { campaigns: 7, editorials: 16, runways: 3 },
  },
]
